spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/navi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /**




  resources:
    static-locations: classpath:/static/



  thymeleaf:
    prefix: classpath:/templates/
    servlet.content-type: text/html
    suffix: .html
    cache: false